version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  restic-backup:
    build:
      context: ..
    entrypoint:
      - sleep
      - infinity
    environment:
      RESTIC_REPOSITORY: /restic-repo
      RESTIC_PASSWORD: supersecret
      POSTGRES_HOST: postgres
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DUMP_FILE: db_dump.sql
      TELEGRAM_NOTIFY_ALWAYS: "true"
    volumes:
      - ./test-data:/data
      - ./test-restic-repo:/restic-repo
    depends_on:
      - postgres

volumes:
  pgdata:
