name: Build and Push Docker Image

on:
  push:
    tags:
      - '*_*'  # Matches tags like my-image_v0.0.1

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name and version from tag
        id: extract
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          IMAGE_NAME="${TAG%%_*}"
          VERSION="${TAG#*_}"
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ steps.extract.outputs.image_name }}
          VERSION=${{ steps.extract.outputs.version }}
          IMAGE_PATH="images/${IMAGE_NAME}"
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${VERSION}"
          IMAGE_TAG_LATEST="ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:latest"

          docker build -t "$IMAGE_TAG" -t "$IMAGE_TAG_LATEST" "$IMAGE_PATH"
          docker push "$IMAGE_TAG"
          docker push "$IMAGE_TAG_LATEST"
